# Generated by Django 6.0.2 on 2026-04-16 09:43

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='ContactMessage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('email', models.EmailField(max_length=254)),
                ('message', models.TextField()),
                ('admin_reply', models.TextField(blank=True, null=True)),
                ('status', models.CharField(choices=[('new', 'جدید'), ('answered', 'پاسخ داده شده')], default='new', max_length=10)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('replied_at', models.DateTimeField(blank=True, null=True)),
            ],
        ),
    ]
